### ISSUE TITLE
Error listing previously imported files - main query syntax error

### ISSUE THREAD

**Issue by pongraczi** [laravel-enso/data-import#14]
Error message (and empty table):  
> You have to add in the main query 'id as "dtRowId"' for the actions to work

Problematic query:  
https://github.com/laravel-enso/DataImport/blob/60774e7dcfce34179d1476c44dbc0f7b86fab816/src/app/Tables/Builders/DataImportTable.php#L14-L17

It should be (please note the `\"` around dtRowId and created_by):  
```php
        return DataImport::select(\DB::raw("data_imports.id, data_imports.id as \"dtRowId\", data_imports.type,
                data_imports.original_name, data_imports.comment, data_imports.created_at,
                concat(users.first_name, ' ', users.last_name) as \"created_by\""))
            ->join('users', 'data_imports.created_by', '=', 'users.id');
```

**Comment by pongraczi** [comment]
Anyway, my DB backend is Postgresql.

**Comment by aocneanu** [comment]
This is strange. If you take a look [here](http://www.postgresqltutorial.com/postgresql-concat-function/) you see in their examples that it's clearly not the case

<img width="761" alt="screen shot 2018-05-08 at 13 15 31" src="https://user-images.githubusercontent.com/16073274/39751781-f1181920-52c1-11e8-93e2-84bed3e00a0b.png">

Are the tutorials outdated?

**Comment by pongraczi** [comment]
It should be fresh, as I started from scratch with 2.6.9.  
Anyway, the problem is not the `concat` but the missing double quote around `dtRowId` and `created_by`.  
I think it is a postgresql restriction, you cannot leave double quote. As I can see, mysql behavior is different, it can allow alternative column name without any quote.

**Comment by aocneanu** [comment]
I look for an example that has both concat and column alias. It should work.

Can you tell me how does the query look from the debugbar?

**Comment by pongraczi** [comment]
This is my version:

```sql
select data_imports.id, data_imports.id as "dtRowId", data_imports.type,
data_imports.original_name, data_imports.comment, data_imports.created_at,
concat(users.first_name, ' ', users.last_name) as "created_by" from "data_imports" inner join "users" on "data_imports"."created_by" = "users"."id" limit 10 offset 0
```
Hint:   
> "The SELECT statement has no WHERE clause and could examine many more rows than intended LIMIT without ORDER BY causes non-deterministic results, depending on the query execution plan"

**Comment by aocneanu** [comment]
I was asking for the select without modifications

**Comment by pongraczi** [comment]
Ok, it seems the problem is not with the missing quote on my side, but the alert pops up there is no dtRowId.  
Sorry, it seems it is not postgresql related, give me some minutes, I search it.

**Comment by pongraczi** [comment]
It seems the detection is not working without the double quote:  
Location: `vendor/laravel-enso/vuedatatable/src/app/Classes/Table/Builder.php`

```php
private function checkActions()
    {
        if (count($this->data) === 0) {
            return;
        }

        if (!isset($this->data[0]['dtRowId'])) {
            throw new QueryException(__('You have to add in the main query \'id as "dtRowId"\' for the actions to work'));
        }
    }
```

**Comment by pongraczi** [comment]
The original query:  

```sql
select data_imports.id, data_imports.id as dtRowId, data_imports.type,
data_imports.original_name, data_imports.comment, data_imports.created_at,
concat(users.first_name, ' ', users.last_name) as created_by from "data_imports" inner join "users" on "data_imports"."created_by" = "users"."id" limit 10 offset 0
```

**Comment by aocneanu** [comment]
It cannot be a problem on the php side, for sure.

If you run this query in you postgres db manager, does it work?

**Comment by pongraczi** [comment]
Yes, the original query and the modified are working as expected.

If I change from `dtRowId` to `\"dtRowId\"` it just works, otherwise alert and empty list appears.

![dtrowid-enso](https://user-images.githubusercontent.com/5891983/39754323-1892be10-52c2-11e8-975f-aaa4c688a988.gif)
