### ISSUE TITLE
XML

### ISSUE THREAD

**Issue by curtisdelicata** [laravel-enso/data-import#15]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
XML Import - would this be possible to abstract to import different file formats? I'm looking to use with Gramps XML.

**Comment by aocneanu** [comment]
I never worked with XMLs, but can't you open a XML with excel already? And save it as xlsx?

**Comment by curtisdelicata** [comment]
That could be possible. Unsure of data loss or time required to do manual conversion.

Then I would write a template for each category of import?

**Comment by curtisdelicata** [comment]
I can also export from the software as CSV so I could do that for now. In my case I would prepare / cut the CSV export, import individuals, marriages and families separately then match and merge results. 

XML support in general could be useful still though as the format of the original database is lossless.

**Comment by aocneanu** [comment]
>Unsure of data loss

Should be none.

>time required to do manual conversion

The time required to import one excel file (few minutes for getting the info from a source, filling the template, actual upload) will increase with probably 30-60 seconds for the conversion. You will have to make thousands of imports from xml to start covering the time needed to extend the Data Importer for this.

>Then I would write a template for each category of import?

Exactly.

We will close for now.
