### ISSUE TITLE
MaxExecutionTime setting not applying correctly

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/data-import#16]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
MaxExecutionTime is being calculated incorrectly
![image](https://user-images.githubusercontent.com/932193/46208716-dfc46400-c32b-11e8-8f38-96e5d0a853ef.png)
(screenshot of tests passing after setting `template->maxExecutionTime` to 0)

### Steps to Reproduce

1. Run tests with coverage on a _regular_ machine
2. Note a max execution time of 60 being exceeded.

### Expected behavior

As none of the individual tests got close to the 60second mark; the tests to just continue

### Actual behavior

max execution timeout, roughly 60seconds after the first dataimport test got initialized (so it doesn't seem to reset when being redefined, most likely)

**Comment by aocneanu** [comment]
It's not very clear to me what the problem is. ~The default `max_execution_time` for imports is 100 (config). Did you specifically limit an import to 60 ?~

Edit:

I tried limiting the provided `owners.json` template from the examples package to 2sec. Once I try to import a file with xxxx records this is what the logger reports

```
[2018-09-29 07:31:00] local.ERROR: Maximum execution time of 2 seconds exceeded {"userId":1,"email":"aocneanu@gmail.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Maximum execution time of 2 seconds exceeded at /Users/adi/code/ensov2/vendor/box/spout/src/Spout/Reader/Wrapper/XMLInternalErrorsHelper.php:79)
[stacktrace]
```



As a note this package will be improved soon to work async. The plan is that the user will only wait for the file upload and from that point on everything should happen with queued jobs and the possibility to display real time progress.

**Comment by jlsjonas** [comment]
It's a test-related issue; it seems that the counter doesn't "reset" between the different tests. which makes them fail (if you run them with a coverage report, as that takes significantly longer)

**Comment by aocneanu** [comment]
I really don't know how to replicate this

**Comment by jlsjonas** [comment]
command that caused this:
`C:\laragon\bin\php\php-7.1.20-Win32-VC14-x64\php.exe -d max_execution_time=30000 -dxdebug.coverage_enable=1 path/to/project/vendor/phpunit/phpunit/phpunit --coverage-clover path\to\.PhpStorm2018.2\system\coverage\ProjectName$phpunit_xml.xml --configuration path\to\project\phpunit.xml --teamcity`

(coverage xml doesn't actually exist in the folder it seems' at least not when I check it after or during test)
Maybe Introducing a heavy load on the system while running a coverage report could replicate the behaviour if a regular coverage report doesn't trigger the issue?

**Comment by aocneanu** [comment]
still not able to replicate. will close for now.
