### ISSUE TITLE
Template validation fails with `Sentence cased` table headers

### ISSUE THREAD

**Issue by vmcvlad** [laravel-enso/data-import#17]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
After the latest update to the Data Import package, the field validation fails due to the fact that it no longer converts the table header to `snake_case`.

### Steps to Reproduce
1. Try to import any .xlsx file, having the table headers in `Sentance case`.

### Expected behavior
The validator should convert the table header to `snake_case` before validating.

### Actual behavior
The validator responds with errors, notifying that the snake_cased columns are missing while the Sentence cased columns are extra.

![image](https://user-images.githubusercontent.com/37445394/51249312-96138e00-199b-11e9-963f-b3493781068e.png)

**Comment by aocneanu** [comment]
fixed in 5318e506bcef2466460d04906da4b2347485e8b4
