### ISSUE TITLE
Tests not running

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/data-import#19]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
See screenshot:
<img width="1472" alt="screenshot 2019-01-26 17 37 05" src="https://user-images.githubusercontent.com/7204559/51790093-35513600-2191-11e9-8f89-2ff860107e2f.png">

### Steps to Reproduce
`./vendor/bin/phpunit --filter DataImportTest`

**Comment by aocneanu** [comment]
Are you sure that you’re on the lastest DI? (I pushed earlier a fix for this)

**Comment by aocneanu** [comment]
In the latest deploy all the tests have passed

**Comment by mauthi** [comment]
Oh, i missed 2.15.2
sorry - you can close this

**Comment by aocneanu** [comment]
The issues should Ideally be closed by the OP :P
