### ISSUE TITLE
Update the tests

### ISSUE THREAD

**Issue by aocneanu** [laravel-enso/data-import#8]
The tests need to be updated to work after the refactor

**Comment by DevIonut** [comment]
DataImportTest:

- [x] index
- [x] can_get_summary
- [x] can_upload
- [x] can_download
- [x] can_destroy

- [x] stops_on_errors
- [x] doesnt_stop_on_errors
- [x] get_structure_issues_error_message
- [x] get_extra_sheet_error_message
- [x] get_missing_sheets_error_message
- [x] get_extra_columns_error_message
- [x] get_missing_columns_error_message
- [x] get_exists_in_sheet_error_message
- [x] get_unique_in_column_error_message
- [x] get_duplicate_lines_error_message
- [x] get_entry_limit_error_message
- [x] get_missing_param_error_message

DataImportTemplateTest:

- [x] can_get_template
- [x] store
- [x] show
- [x] can_destroy
